package org.mediasport.matchcenter.docs;

public enum EEventType {
	GOAL, PENALTY, PENALTY_NOGOAL_OUT, PENALTY_NOGOAL_KEEPER, FREEKICK_GOAL, OWNGOAL,YELLOW, RED, SHOOTIN, SHOOTOUT, CORNER, FOUL, COMMENT;
}
